spring:
  application:
    name: server-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.73.130:3306/sa_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: MyNewPass4!
  # 微服务注册中心配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858 # Sentinel控制台服务地址
      web-context-unify: false
server:
  port: 8080
  servlet:
    context-path: /order
  # 首先在这里限制了 Tomcat 最大线程数，然后再进行压力测试才会发现接口响应慢，默认是 200 个线程.
  tomcat:
    threads:
      max: 20

# MyBatis-Plus 配置
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'

# Feign 配置
feign:
  # 开启 Sentinel 配置
  sentinel:
    enabled: true